NEW death squadron
frosty-dev/ss14 pull request #63
Opened 2022-12-25 19:45 UTC by Zavanick

## Описание
В виде черепахи конечно, но на борту ~15 мест для перелета и есть оружейная.
## Скрин
![image](https://user-images.githubusercontent.com/121029968/209480244-e77c4c9d-d007-4b07-817d-5368fa48d469.png)

2022-12-26 12:18 UTC, RavMorgan requested changes
Rhen

2022-12-26 12:18 UTC, RavMorgan commented on Resources/Maps/Shuttles/shuteldestroyder.yml
> +meta:
Check failure on line 1 in Resources/Maps/Shuttles/shuteldestroyder.yml
[/Resources/Maps/Shuttles/shuteldestroyder.yml] entities: Length of [] is less than 1

2022-12-26 22:41 UTC, Zavanick commented on Resources/Maps/Shuttles/shuteldestroyder.yml
> +meta:
У меня вообще как-то странно все сохраняется, у меня мои же шаттлы на Инфинити не загружаются, которые я на сервере сохрранял

2022-12-29 18:56 UTC, wCATw commented
Если че откроете потом

2022-12-29 18:56 UTC, closed without merging